FoodTickets/Models/FoodTickets.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTickets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodTicketsEntities : DbContext
    {
        public FoodTicketsEntities()
            : base("name=FoodTicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meal> Meals { get; set; }
    }
}

FoodTickets/Models/FoodTickets.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Simon Costea\source\repos\FoodTickets - Copy\FoodTickets\Models\FoodTickets.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

FoodTickets/Models/FoodTickets.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

FoodTickets/Models/Meal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealID { get; set; }
        public int PersonID { get; set; }
        public int MealType { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Taken { get; set; }
    }
}

FoodTickets/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoodTickets.Models;

namespace FoodTickets.Controllers
{
    public class RegisterController : Controller
    {
        FoodTicketsEntities db = new FoodTicketsEntities();
        // GET: Register
        public ActionResult SetDataInDataBase()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SetDataInDataBase(Meal model)
        {
            Meal tbl = new Meal();
            tbl.PersonID = model.PersonID;
            tbl.MealType = model.MealType;
            tbl.Date = model.Date;
            db.Meals.Add(tbl);
            db.SaveChanges();
            return View();
        }

        public ActionResult ShowDataBaseForUser()
        {
            var item = db.Meals.ToList();
            return View(item);
        }
        public ActionResult Delete(int id)
        {
            var item = db.Meals.Where(x => x.MealID == id).First();
            db.Meals.Remove(item);
            db.SaveChanges();
            var item2 = db.Meals.ToList();
            return View("ShowDataBaseForUser", item2);
        }
        public ActionResult Edit(int id)
        {
            var item = db.Meals.Where(x => x.MealID == id).First();
            if(item.Taken == 1)
            {
                return View("AlreadyTaken");
            } else
            {
                item.Taken = 1;
                db.SaveChanges();
                return View("Succes");            
                //return View(item);
            }
        }
        [HttpPost]
        public ActionResult Edit(Meal model)
        {
            var item = db.Meals.Where(x => x.MealID == model.MealID).First();
            item.PersonID = model.PersonID;
            item.MealType = model.MealType;
            item.Date = model.Date;
            item.Taken = model.Taken;          
            db.SaveChanges();
            return View();
        }
    }
}

FoodTickets/Views/Register/AlreadyTaken.cshtml
@{
    ViewBag.Title = "AlreadyTaken";
}

<h2>AlreadyTaken</h2>

<p>You have already had this meal.</p>
<i class="glyphicon-remove" style="font-size:50px; color: red;"></i>

FoodTickets/Views/Register/Edit.cshtml
@model FoodTickets.Models.Meal
@using (Html.BeginForm())
{
    <div class="container">
        @Html.HiddenFor(x => x.MealID, new { @class = "form-control" })
        <div class="form-group">
            <label>PersonID:</label>
            @Html.TextBoxFor(x => x.PersonID, new { @class="form-control" })
        </div>
        <div class="form-group">
            <label>MealType:</label>
            @Html.TextBoxFor(x => x.MealType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Date:</label>
            @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Taken:</label>
            @Html.TextBoxFor(x => x.Taken, new { @class = "form-control" })
        </div>
        <div class="button">
            <button>Submit</button>
        </div>
    </div>
}

FoodTickets/Views/Register/SetDataInDataBase.cshtml
@model FoodTickets.Models.Meal
@using (Html.BeginForm())
{
    <div class="container">
        <div class="form-group">
            <label>PersonID:</label>
            <input class="form-control" name="PersonID" placeholder="Enter Person ID" />
        </div>
        <div class="form-group">
            <label>MealType:</label>
            <input class="form-control" name="MealType" placeholder="Enter MealType" />
        </div>
        <div class="form-group">
            <label>Date:</label>
            <input class="form-control" name="Date" placeholder="Enter Date" />
        </div>
        <div class="button">
            <button>Submit</button>
        </div>
    </div>
}

FoodTickets/Views/Register/ShowDataBaseForUser.cshtml
@model List<FoodTickets.Models.Meal>
    <div class="container">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>PersonID</th>
                    <th>MealType</th>
                    <th>Date</th>
                    <th>Taken</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for(int i=0; i<Model.Count(); i++)
                {
                    <tr>
                        <td>@Model[i].PersonID</td>
                        <td>@Model[i].MealType</td>
                        <td>@Model[i].Date</td>
                        <td>@Model[i].Taken</td>
                        <td>
                            <a href="@Url.Action("Delete", new { id = Model[i].MealID })"><i class="glyphicon glyphicon-trash"></i></a>
                            <a href="@Url.Action("Edit", new { id = Model[i].MealID })"><i class="glyphicon glyphicon-edit"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

FoodTickets/Views/Register/Succes.cshtml
<i class="glyphicon-check" style="font-size:50px; color: green;"></i>

FoodTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "", "", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "", "")</li>
                    <li>@Html.ActionLink("ListOfMeals", "ShowDataBaseForUser", "Register")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>